/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SUM_H_RPCGEN
#define _SUM_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct sum_data {
	int x;
	int y;
};
typedef struct sum_data sum_data;

#define SUM_PROG 1
#define SUM_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define get_sum 1
extern  int * get_sum_1(struct sum_data *, CLIENT *);
extern  int * get_sum_1_svc(struct sum_data *, struct svc_req *);
extern int sum_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define get_sum 1
extern  int * get_sum_1();
extern  int * get_sum_1_svc();
extern int sum_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_sum_data (XDR *, sum_data*);

#else /* K&R C */
extern bool_t xdr_sum_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SUM_H_RPCGEN */
