/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCINTERFACE_H_RPCGEN
#define _RPCINTERFACE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct request_data {
	char *user_id;
	char *request_token;
	char *op_type;
	char *resource;
	char *access_token;
};
typedef struct request_data request_data;

struct response_data {
	char *request_token;
	char *access_token;
	char *refresh_token;
	char *permision_response;
};
typedef struct response_data response_data;

#define REQUEST_AUTH_PROG 1
#define REQUEST_AUTH_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define request_auth 1
extern  response_data * request_auth_1(struct request_data *, CLIENT *);
extern  response_data * request_auth_1_svc(struct request_data *, struct svc_req *);
#define request_access 2
extern  response_data * request_access_1(struct request_data *, CLIENT *);
extern  response_data * request_access_1_svc(struct request_data *, struct svc_req *);
#define validate_action 3
extern  response_data * validate_action_1(struct request_data *, CLIENT *);
extern  response_data * validate_action_1_svc(struct request_data *, struct svc_req *);
#define approve_request 4
extern  response_data * approve_request_1(struct request_data *, CLIENT *);
extern  response_data * approve_request_1_svc(struct request_data *, struct svc_req *);
extern int request_auth_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define request_auth 1
extern  response_data * request_auth_1();
extern  response_data * request_auth_1_svc();
#define request_access 2
extern  response_data * request_access_1();
extern  response_data * request_access_1_svc();
#define validate_action 3
extern  response_data * validate_action_1();
extern  response_data * validate_action_1_svc();
#define approve_request 4
extern  response_data * approve_request_1();
extern  response_data * approve_request_1_svc();
extern int request_auth_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_request_data (XDR *, request_data*);
extern  bool_t xdr_response_data (XDR *, response_data*);

#else /* K&R C */
extern bool_t xdr_request_data ();
extern bool_t xdr_response_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPCINTERFACE_H_RPCGEN */
