/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "rpcinterface.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

response_data *
request_auth_1(struct request_data *argp, CLIENT *clnt)
{
	static response_data clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, request_auth,
		(xdrproc_t) xdr_request_data, (caddr_t) argp,
		(xdrproc_t) xdr_response_data, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

response_data *
request_access_1(struct request_data *argp, CLIENT *clnt)
{
	static response_data clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, request_access,
		(xdrproc_t) xdr_request_data, (caddr_t) argp,
		(xdrproc_t) xdr_response_data, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

response_data *
validate_action_1(struct request_data *argp, CLIENT *clnt)
{
	static response_data clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, validate_action,
		(xdrproc_t) xdr_request_data, (caddr_t) argp,
		(xdrproc_t) xdr_response_data, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

response_data *
approve_request_1(struct request_data *argp, CLIENT *clnt)
{
	static response_data clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, approve_request,
		(xdrproc_t) xdr_request_data, (caddr_t) argp,
		(xdrproc_t) xdr_response_data, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
