/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "check.h"


void
checkprog_1(char *host)
{
	CLIENT *clnt;
	char * *result_1;
	student  grade_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CHECKPROG, CHECKVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

    grade_1_arg.nume = malloc(50);
    if (grade_1_arg.nume == NULL) {
        clnt_perror (clnt, "malloc failed");
    }
    grade_1_arg.grupa = malloc(10);
    if (grade_1_arg.grupa == NULL) {
        clnt_perror (clnt, "malloc failed");
    }
    strcpy(grade_1_arg.nume, "Rotaru Petru-Alexandru");
    strcpy(grade_1_arg.grupa, "341C3");
	result_1 = grade_1(&grade_1_arg, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
    printf("%s\n", *result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	checkprog_1 (host);
exit (0);
}
