version: "3.3"

services:
    mosquitto:
        #container_name: mosquitto
        image: eclipse-mosquitto:1.6
        ports:
            - '1883:1883'
        networks:
            - mosquitto-adapter

    database:
        #container_name: database
        image: influxdb:1.8-alpine
        ports:
            - '8086:8086'
        volumes:
            - influxdb_data:/var/lib/influxdb
        networks:
            - adapter-database
            - database-grafana

    adapter:
        #container_name: adapter
        #build: ./adapterMQTT-DB
        image: adapter
        volumes:
            - ./adapterMQTT-DB:/adapterMQTT-DB
        environment:
            - DEBUG_DATA_FLOW=true
        depends_on:
            - mosquitto
            - database
        networks:
            - mosquitto-adapter
            - adapter-database

    grafana:
        #container_name: grafana
        image: grafana/grafana:latest
        ports:
            - '80:3000'
        volumes:
            - grafana_data:/var/lib/grafana
            - ${SPRC_DVP}/provisioning/:/etc/grafana/provisioning
        environment:
            - GF_SECURITY_ADMIN_USER=asistent
            - GF_SECURITY_ADMIN_PASSWORD=grafanaSPRC2021
        depends_on:
            - database
        networks:
            - database-grafana

volumes:
    influxdb_data:
    grafana_data:

networks:
    mosquitto-adapter:
    adapter-database:
    database-grafana:


