version: '3.3'

services:
  database:
    container_name: database_container
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  db_data:
    driver: local
  pgadmin_data:
    driver: local