/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SUM_H_RPCGEN
#define _SUM_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct int_pair {
	int a;
	int b;
};
typedef struct int_pair int_pair;

#define SUM 210199617
#define SUM_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define GET_SUM 1
extern  int * get_sum_1(int_pair *, CLIENT *);
extern  int * get_sum_1_svc(int_pair *, struct svc_req *);
extern int sum_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_SUM 1
extern  int * get_sum_1();
extern  int * get_sum_1_svc();
extern int sum_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_int_pair (XDR *, int_pair*);

#else /* K&R C */
extern bool_t xdr_int_pair ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SUM_H_RPCGEN */
