/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "sum.h"


void
sum_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	int_pair  get_sum_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SUM, SUM_V1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

    while (1) {
        printf("a = ");
        scanf("%d", &get_sum_1_arg.a);
        printf("\nb = ");
        scanf("%d", &get_sum_1_arg.b);
        printf("\n");
        result_1 = get_sum_1(&get_sum_1_arg, clnt);
        if (result_1 == (int *) NULL) {
            clnt_perror(clnt, "call failed");
        }

        printf("CLIENT: %d + %d = %d\n", get_sum_1_arg.a, get_sum_1_arg.b, *result_1);
    }
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */

}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	sum_1 (host);
exit (0);
}
